# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  # Archives: /archives/
  # Tags: /tags/
  # Categories: /categories/
  About: /about/me
  Links: /links

# hexo-tag-cloud
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColor: '#2a6496' #'#e6e6e6'
  textHeight: 18
  outlineColor: '#2a6496'
  maxSpeed: 0.1
  shadow: '#2a6496'

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# 代码高亮设置
syntax_highlighter: highlight.js
highlight:
  auto_detect: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
  exclude_languages:
    - example
  wrap: true
  hljs: false

# default page mode: default | archives
mode: archives

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: blackbear03.w@gmail.com
  stack-overflow:
  twitter: https://twitter.com/blackbear_03
  facebook:
  linkedin:
  google:
  github: https://github.com/blackbear03
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics: '8ee5fa5409f3df806c00a4afa80773da'
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# busuanzi Analytics
busuanzi:
 enable: true
# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: GitHub repo owner
  repo: GitHub repo
  client_id: GitHub Application Client ID
  client_secret: GitHub Application Client Secret
  admin_user: GitHub repo owner and collaborators, only these guys can initialize github issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# utterances
# Docs: https://utteranc.es/
# Tips: Make sure you have installed [utterances app](https://github.com/apps/utterances) in your repo
utterances:
  enable: true
  repo: blackbear03/blackbear03.github.io # Repository
  issueTerm: title  # Blog post ↔️ issue mapping: pathname | url | title | og:title
  theme: github-dark # Theme: github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  label: utterances # Issue label

# ===========================================
# Version
# ===========================================
version: 2.11.0